ALTER TABLE __CLICKHOUSE_DATABASE__.events
  ADD COLUMN IF NOT EXISTS user_email String DEFAULT '';

ALTER TABLE __CLICKHOUSE_DATABASE__.events
  ADD COLUMN IF NOT EXISTS user_username String DEFAULT '';
